### ISSUE TITLE
Session Bugs

### ISSUE THREAD

**Issue by Caposto** [Web-Dev-x-Blueprint/cs554-final-project#34]
- After first seeding, session is not loaded until refreshing the page
- After logging in as an Admin, logging out, and then logging in as a Mentor, admin pages were still visible until refreshed

This might be a potential fix: https://leyanlo.medium.com/how-to-reset-react-context-473cb2e0fab6

**Comment by RyanCamburn** [comment]
Fixed with this code in app/page.tsx

`const router = useRouter();
  useEffect(() => {
    // Clears the Routing Cache, so admin dashboard appers for the users with the right permissions
    router.refresh();
  }, [router]);`
